# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Dev-Environment-Variables-Group
  - name: enviornmentName
    value: dev

steps:
- task: AzureCLI@2
  displayName: 'Update Azure CLI and Bicep'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade
      az bicep upgrade
      az bicep version

- task: AzureCLI@2
  displayName: 'Create Hub network resources'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-02-network-hub' --location $(azureregion) `
      --parameters  './02-Network-Hub/main.bicepparam' `
      --parameters rgName=$(hubNetworkResourceGroup)

- task: AzureCLI@2
  displayName: 'Update UDR for Hub network resources'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-02-network-hub-updateUDR' --location $(azureregion) `
      --parameters  './02-Network-Hub/updateUDR.bicepparam' `
      --parameters rgName=$(hubNetworkResourceGroup)

- task: AzureCLI@2
  displayName: 'Create AKS spoke network resources'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-03-network-spoke' --location $(azureregion) `
      --parameters  './03-Network-LZ/main.bicepparam' `
      --parameters rgName=$(SpokeNetworkResourceGroup) hubSubscriptionId=$(HubSubscriptionId)

- task: AzureCLI@2
  displayName: 'Update UDR and NSG for spoke network resources'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-network-spoke-updateUDR' --location $(azureregion) `
      --parameters  './03-Network-LZ/updateUDR-NSG.bicepparam' `
      --parameters rgName=$(SpokeNetworkResourceGroup)

- task: AzureCLI@2
  displayName: 'Create AKS supporting service'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-04-aks-supporting' --location $(azureregion) `
      --parameters  './04-AKS-Supporting/main.bicepparam' `
      --parameters rgName=$(AKSResourceGroup) rgSpokevnetName=$(SpokeNetworkResourceGroup) `
      --parameters storageAccountName=$(StorageAccountName) privatednszonesSubscriptionId=$(PrivateDNSSubscriptionId) acrName=$(ACRName)

- task: AzureCLI@2
  displayName: 'Create AKS service'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-05-aks-deployment' --location $(azureregion) `
      --parameters  './05-AKS/main.bicepparam' `
      --parameters rgName=$(AKSResourceGroup) privateDNSZoneAKSNameResourceGroup=$(SpokeNetworkResourceGroup) `
      --parameters vnetspokeRGName=$(SpokeNetworkResourceGroup) aksadminGroupaccessprincipalId=$(AdminsGroupId) `
      --parameters aksusersgroupaccessprincipalId=$(UsersGroupId)  privateDNSZoneAKSNameSubscriptionId=$(PrivateDNSSubscriptionId) `
      --parameters acrName=$(ACRName)
