# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  - group: Dev-Environment-Variables-Group
  - name: enviornmentName
    value: dev

steps:
- task: AzureCLI@2
  displayName: 'Update Azure CLI and Bicep'
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az upgrade
      az bicep upgrade
      az bicep version

- task: AzureCLI@2
  inputs:
    azureSubscription: 'azdemoconnection'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment sub create --name '$(enviornmentName)-02-network-hub' --location $(azureregion) `
      --parameters  './02-Network-Hub/main.bicepparam' `
      --parameters rgName=$(hubNetworkResourceGroup)
